with-expecter: true
dir: "./mocks"
outpkg: "mocks"
mockname: "Mock{{.InterfaceName}}"
filename: "mock_{{.InterfaceName | lower}}.go"
structname: "Mock{{.InterfaceName}}"
boilerplate-file: ""
log-level: info

packages:
  "audit-service/internal/service":
    interfaces:
      AuditService:
        filename: "mock_audit_service.go"
        mockname: "MockAuditService"
        structname: "MockAuditService"
  
  "audit-service/internal/repository":
    interfaces:
      AuditRepository:
        filename: "mock_audit_repository.go"
        mockname: "MockAuditRepository"
        structname: "MockAuditRepository"
  
  "audit-service/pkg/jwt":
    interfaces:
      TokenValidator:
        filename: "mock_token_validator.go"
        mockname: "MockTokenValidator"
        structname: "MockTokenValidator" 