version: "3.8"

services:
  audit-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: audit-service
    ports:
      - "4006:4006"
    environment:
      - PORT=4006
      - LOG_LEVEL=debug
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
      - HTTP_TIMEOUT=30s
      - HTTP_MAX_IDLE_CONNS=100
      - HTTP_MAX_CONNS_PER_HOST=10
      - HTTP_IDLE_CONN_TIMEOUT=90s
      - CACHE_JWT_TTL=5m
      - CACHE_SHARE_TOKEN_TTL=1m
      - CACHE_CLEANUP_INTERVAL=10m
      - MAX_PAGE_SIZE=100
      - DEFAULT_PAGE_SIZE=50
    networks:
      - audit-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:4006/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  audit-network:
    driver: bridge
